service: nest-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${ssm:/topstats-api/dev/NODE_ENV}
    PORT: ${ssm:/topstats-api/dev/PORT}
    API_CONTEXT: ${ssm:/topstats-api/dev/API_CONTEXT}
    MONGODB_URI: ${ssm:/topstats-api/dev/MONGODB_URI}
    API_SPOTIFY_CLIENT_ID: ${ssm:/topstats-api/dev/API_SPOTIFY_CLIENT_ID}
    API_SPOTIFY_CLIENT_SECRET: ${ssm:/topstats-api/dev/API_SPOTIFY_CLIENT_SECRET}
    HOST_ACCOUNTS_API_SPOTIFY: ${ssm:/topstats-api/dev/HOST_ACCOUNTS_API_SPOTIFY}
    HOST_API_SPOTIFY: ${ssm:/topstats-api/dev/HOST_API_SPOTIFY}
    REDIRECT_URI_CALLBACK: ${ssm:/topstats-api/dev/REDIRECT_URI_CALLBACK}
    API_SPORIFY_USER_SCOPE: ${ssm:/topstats-api/dev/API_SPORIFY_USER_SCOPE}
    HOST: ${ssm:/topstats-api/dev/HOST}
    HOST_FRONTEND: ${ssm:/topstats-api/dev/HOST_FRONTEND}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: arn:aws:ssm:us-east-1:*:parameter/topstats-api/dev/*

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
          private: true

plugins:
  - serverless-offline

package:
  patterns:
    - 'dist/**'
    - 'node_modules/@vendia/**'
    - 'node_modules/@codegenie/**'
    - 'node_modules/@nestjs/**'
    - 'node_modules/express/**'
    - '!**/*.spec.ts'
    - '!src/**'
  exclude:
    - .env
    - .env.*
